apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  NODE_ENV: "production"
  API_PORT: "4000"
  WEB_PORT: "3000"
  OPENSEARCH_URL: "http://{{ .Values.opensearch.host }}:{{ .Values.opensearch.port }}"
  NATS_URL: {{ .Values.nats.url | quote }}
  TEMPORAL_ADDRESS: {{ .Values.temporal.address | quote }}
  TEMPORAL_NAMESPACE: "privacyops"
  S3_REGION: {{ .Values.s3.region | quote }}
  S3_BUCKET: {{ .Values.s3.bucket | quote }}
  CORS_ORIGINS: "https://app.privacyops.techd.com"
